describe('first',()=>{
    it('second',()=>{
        cy.visit(' http://localhost:5173/')
 
              cy.url().should ('eq','http://localhost:5173/')
        cy.get('.grow > :nth-child(2) > .font-medium').click()
              cy.url().should('eq',"http://localhost:5173/signin")
        cy.get(':nth-child(3) > .text-gray-600').click()
        cy.get('#username').type("srivathsandv2")
        cy.get('#password').type("1SDE@mayim")
        cy.get('.btn').click()
        cy.visit("http://localhost:5173/maindashboard")
        cy.reload()
        cy.get('[href="/inventory"] > .MuiListItemIcon-root').click()
                   cy.url().should('eq','http://localhost:5173/inventory')
        cy.get('.MuiGrid-container > :nth-child(3) > .MuiButtonBase-root').click()
        cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
        cy.get('[data-value="2"]').click()
        cy.get('.MuiDialogContent-root > .MuiGrid-container > :nth-child(3)').type("dolo650")
        cy.get('.MuiGrid-container > :nth-child(5)').type(12.00)
        cy.get('.MuiGrid-container > :nth-child(7)').type("used for cold and fever")
        cy.get('.MuiGrid-container > :nth-child(5)').type("")
    })
})