describe('user',()=>{
    it('name',()=>{
    cy.visit(' http://localhost:5173/')    
 cy.get('.grow > :nth-child(2) > .font-medium').click()
cy.get('.justify-center > :nth-child(3)').click()
cy.get('#username').type('srivathsandv2')
cy.get('#password').type('1SDE@mayim')
cy.get('.btn').click()
cy.wait(1000)
cy.reload()
cy.get('.MuiToolbar-root > .MuiTypography-root').click()
cy.url().should('eq','http://localhost:5173/maindashboard')
cy.get('[href="/hsd"] > .MuiListItemText-root > .MuiTypography-root').click()
cy.url().should('eq','http://localhost:5173/hsd')
cy.get('[data-id="100003"] > [data-field="action"] > .cellAction > .viewbutton').click()
cy.get('[data-testid="EditIcon"]').click()
cy.get('.MuiDialogContent-root > :nth-child(2) > :nth-child(6)').clear().type("visrutha@122")
cy.get(':nth-child(2) > :nth-child(7)').clear().type("visrutha US")
cy.get(':nth-child(2) > :nth-child(9)').clear().type("9876543210")
cy.get(':nth-child(2) > :nth-child(10)').clear().type("2587469317")
cy.get(':nth-child(2) > :nth-child(11)').clear().type("zyx@gmail.com")
cy.get('.MuiDialogActions-root > .MuiGrid-container > :nth-child(2) > :nth-child(1)').click()
cy.on('window:alert', (text) => {
    expect(text).to.contains('Please fill in all required fields.')
   })
})
})