describe('open',() =>{
    it('verify',() =>{
        cy.log("visit the website")
        cy.visit(' http://localhost:5173/')
        cy.title().should('eq','VET CASTLE')
     cy.url().should('eq','http://localhost:5173/')
        cy.get('.grow > :nth-child(1) > .font-medium').click()
        cy.url().should('eq','https://localhost:5173/pricing')
        cy.get(':nth-child(1) > .btn-sm').click()
        cy.url().should('eq','https://localhost:5173/gsignup')
    })
    it('verify',() =>{
        cy.log("visit the website")
        cy.visit(' http://localhost:5173/')
        cy.title().should('eq','VET CASTLE')
     cy.url().should('eq','http://localhost:5173/')
        cy.get('.grow > :nth-child(1) > .font-medium').click()
        cy.url().should('eq','https://localhost:5173/pricing')
        cy.get(':nth-child(2) > .btn-sm').click()
        cy.url().should('eq','https://localhost:5173/dsignup')
    })
    it('verify',() =>{
        cy.log("visit the website")
        cy.visit(' http://localhost:5173/')
        cy.title().should('eq','VET CASTLE')
     cy.url().should('eq','http://localhost:5173/')
        cy.get('.grow > :nth-child(1) > .font-medium').click()
        cy.url().should('eq','https://localhost:5173/pricing')
        cy.get('.max-w-sm > :nth-child(3) > .btn-sm').click()
        cy.url().should('eq','https://localhost:5173/psignup')
    })
})