name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install --force
      
      - name: Install Cypress
        run: npm install cypress --save-dev --force
      
      - name: Start API server
        run: |
          Start-Process "npm" -ArgumentList "run start-api" -NoNewWindow
          timeout /t 10
      
      - name: Start web server
        run: |
          Start-Process "npm" -ArgumentList "run start-web" -NoNewWindow
          timeout /t 10
      
      - name: Run Cypress tests
        run: npx cypress run

