name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 1Time@p!
          MYSQL_DATABASE: tfeiamho_vetcastle

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Cypress
        run: npx cypress install

      - name: Wait for MySQL to be ready and create the database
        run: 
          mysql -h"127.0.0.1" -uroot -p1Time@p! -e "CREATE DATABASE IF NOT EXISTS tfeiamho_vetcastle;"
       
      
      - name: Start API server
        run: |
          cd web/apis
          npm install
          nohup npm start &
          npx wait-on http://localhost:3000
        
      
      - name: Start web server
        run: |
          cd web/webapp
          npm install --legacy-peer-deps
          nohup npm run dev &
          npx wait-on http://localhost:8080
        shell: bash
      
      - name: Cypress run
        run: npx cypress run
