name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: tfeiamho_vetcastle
          MYSQL_PASSWORD: 1Time@p!

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install --force

      - name: Install Cypress
        run: npm install cypress --save-dev --force

      - name: Wait for MySQL to be ready
        run: sleep 30 # Adjust this based on how long MySQL needs to start

      - name: Start API server
        shell: pwsh
        run: |
          cd web/apis
          npm install
          start-process npm -ArgumentList 'start' -NoNewWindow
          Start-Sleep -Seconds 10
      
      - name: Start web server
        shell: pwsh
        run: |
          cd web/webapp
          npm install --legacy-peer-deps
          start-process npm -ArgumentList 'start' -NoNewWindow
          Start-Sleep -Seconds 10
      
      - name: Wait for servers to be ready
        run: timeout /t 30 # Adjust the time as needed to ensure servers are up
      
      - name: Run Cypress tests
        run: npx cypress run
      
      - name: Stop servers
        if: always()
        run: taskkill /IM "node.exe" /F


      
      - name: Stop servers
        if: always()
        run: taskkill /IM "node.exe" /F

